var iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream;var plancheAuto,plancheAutoHide,planche={elements:{},options:{showTime:2000,startDelay:4000,closeButtonClosesShow:!0},showTimeout:0,restartAnimTimeout:0,autoShowTimeout:0,flags:{shown:!1,displayCounter:0,active:!0,movieClosed:!1},onComplete:null,noImage:!1,showItTimeout:0,initPlanche:function(options){o=planche.options;o=$.extend(o,options);if(o.boardAggressive){o.showTime=2500;o.startDelay=0;o.plancheInterval=undefined;o.closeButtonClosesShow=!1}
e=planche.elements;planche.cachePlancheElem();planche.bindPlancheUIActions();planche.plancheAnim.hidden();e.plancheClose.css('user-select','none');e.planche.css('user-select','none');planche.vid=document.getElementById('movie');if(planche.vid&&iOS)planche.vid.controls=!0;if(o.startDelay>0){planche.enabled=planche.flags.active=!1;setTimeout(function(){planche.enabled=planche.flags.active=!0;o.startDelay=0;initAnim()},o.startDelay)}else{planche.enabled=!0;initAnim()}
function initAnim(){if(!o.enlargerAnimEnabled||o.enlargeHover)planche.autoShow()}},cachePlancheElem:function(){e.planche=$('#banner-planche'),e.plancheClose=$('.planche-close');e.audioButton=$('#audio-button');e.noAudio=$('.no-audio');e.audio=$('.audio')},bindPlancheUIActions:function(){e.planche.on('mouseenter',function(ev){e.audioButton.css('opacity',1)
ev.preventDefault()});e.planche.on('mouseleave',function(ev){e.audioButton.css('opacity',isMobile?'0.5':'')
ev.preventDefault()});e.audioButton.on('click',function(){if(planche.vid){planche.vid.muted=!planche.vid.muted;e.noAudio.css('opacity',Number(planche.vid.muted));e.audio.css('opacity',Number(!planche.vid.muted));if(isMobile){if(planche.fadeOutTimOut)clearTimeout(planche.fadeOutTimOut);planche.fadeOutTimOut=setTimeout(function(){e.audioButton.css('opacity','0.5')},1000)}}});e.plancheClose.on('click',function(ev){planche.vid.pause();planche.onComplete=undefined;planche.plancheAnim.hide();if(o.closeButtonClosesShow)planche.enabled=planche.flags.active=!1})},showIt:function(el,ok,t,onComplete){t=t||300;if(ok){el.css('opacity','0').css('display','block').css('transform','translateX(-20px)').css('left','0')}
el.css('transition-property','transform, opacity').css('transition-duration',((t-16)/1000)+'s')
setTimeout(function(){el.css('opacity',ok?'1':'0').css('transform',ok?'translateX(0px)':'translateX(20px)')},16);clearTimeout(planche.showItTimeout)
planche.showItTimeout=setTimeout(function()
{el.css('transition-property','none').css('transform','none');if(onComplete)onComplete()},t)},plancheAnim:{show:function(){planche.flags.shown=!0;planche.enabled=planche.flags.active=!1;if(supportTransition){planche.showIt(e.planche,!0)}else{e.planche.css('display','block').anim({left:0,opacity:1})}},hide:function(){if(!planche.flags.shown)return;planche.flags.movieClosed=!0;planche.flags.shown=!1;clearTimeout(planche.showTimeout);if(supportTransition){planche.showIt(e.planche,!1,300,planche.plancheAnim.hidden)}else{e.planche.anim({left:20,opacity:0},{duration:300,complete:planche.plancheAnim.hidden})}
if(planche.vid)planche.vid.pause();if(planche.onComplete)planche.onComplete()},hidden:function(){if(!supportTransition)e.planche.css('left','-20px');e.planche.css('opacity','0').css('display','none')}},autoShow:function(){if(!planche.flags.active)return;planche.makeShow();if(planche.autoShowTimeout)clearTimeout(planche.autoShowTimeout);planche.autoShowTimeout=setTimeout(planche.autoShow,o.boardInterval?o.boardInterval+o.showTime:o.showTime*3)},makeShow:function(onComplete,shown){if(o.startDelay>0)return;if(!planche.flags.shown){if(onComplete)planche.onComplete=onComplete;if(planche.vid)loadMovie()}
planche.showTimeout=setTimeout(function(){planche.plancheAnim.hide();if(onComplete)onComplete()},o.showTime);function loadMovie(){clearTimeout(planche.showTimeout);planche.vid.play();planche.vid.muted=!0;e.audioButton.css('opacity',isMobile?'0.5':'')
function waitForMovie(){if(planche.vid.readyState>0){if(o.coverVideo)planche.coverVideo();planche.plancheAnim.show();planche.vid.play();waitForEnd()}else{setTimeout(waitForMovie,100)}}
function waitForEnd(){if(planche.vid.ended){planche.plancheAnim.hide()}else{if(planche.flags.movieClosed)return;setTimeout(waitForEnd,100)}}
waitForMovie()}},coverVideo:function(){var vw=planche.vid.videoWidth,vh=planche.vid.videoHeight,bw=bannerWidth,bh=bannerHeight,nw,nh;var div=$('#banner-planche div div');if(vw/bw>vh/bh){nw=(vw/vh)*bh;nh=bh}else{nh=(vh/vw)*bw;nw=bw}
div.css('width',nw+'px').css('height',nh+'px').css('margin-left',(bw-nw)/2+'px').css('margin-top',(bh-nh)/2+'px')}}